# cursor--Update: Docker Compose file to run PostgreSQL, backend, and frontend containers for landing page.
services:
  postgres:
    image: postgres:13
    container_name: landingpage_postgres
    environment:
      POSTGRES_USER: postgres       # Ensure these match your .env values
      POSTGRES_PASSWORD: postgres   # Ensure these match your .env values
      POSTGRES_DB: alchemorsel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: landingpage_backend
    env_file:
      - ./backend/.env  # Load environment variables from .env file
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: landingpage_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs_volume:/etc/letsencrypt
    restart: always

volumes:
  postgres_data:
